[package]
name = "nils-agent-out"
version = "1.28.6"
edition.workspace = true
license.workspace = true

description = "CLI crate for nils-agent-out in the nils-cli workspace."
repository = "https://github.com/sympoies/nils-cli"

[lib]
name = "agent_out"
path = "src/lib.rs"

[[bin]]
name = "agent-out"
path = "src/main.rs"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
clap = { workspace = true }
clap_complete = { workspace = true }
nils-build-info = { version = "1.28.6", path = "../nils-build-info" }
nils-common = { version = "1.28.6", path = "../nils-common", package = "nils-common" }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
nils-test-support = { version = "1.28.6", path = "../nils-test-support" }
pretty_assertions = { workspace = true }
tempfile = "3"
