[package]
name = "nils-macos-agent"
version = "1.28.15"
edition.workspace = true
license.workspace = true

description = "CLI crate for nils-macos-agent in the nils-cli workspace."
repository = "https://github.com/sympoies/nils-cli"

[lib]
name = "macos_agent"
path = "src/lib.rs"

[[bin]]
name = "macos-agent"
path = "src/main.rs"
[dependencies]
base64 = "0.23"
clap = { workspace = true }
clap_complete = { workspace = true }
nils-build-info = { version = "1.28.15", path = "../nils-build-info" }
jiff = { workspace = true }
libc = "0.2"
roxmltree = "0.21"
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
nils-common = { version = "1.28.15", path = "../nils-common", package = "nils-common" }

[dev-dependencies]
pretty_assertions = { workspace = true }
nils-test-support = { version = "1.28.15", path = "../nils-test-support" }
tempfile = "3"
