[package]
name = "nils-git-cli"
version = "1.28.7"
edition.workspace = true
license.workspace = true

description = "CLI crate for nils-git-cli in the nils-cli workspace."
repository = "https://github.com/sympoies/nils-cli"

[lib]
name = "git_cli"
path = "src/lib.rs"

[[bin]]
name = "git-cli"
path = "src/main.rs"
[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
getrandom = { workspace = true }
git-summary = { version = "1.28.7", path = "../git-summary", package = "nils-git-summary" }
libc = { workspace = true }
nils-build-info = { version = "1.28.7", path = "../nils-build-info" }
nils-common = { version = "1.28.7", path = "../nils-common", package = "nils-common" }
serde = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"] }
sha2 = { workspace = true }
thiserror = { workspace = true }
time = { version = "0.3", features = ["formatting"] }

[dev-dependencies]
nils-test-support = { version = "1.28.7", path = "../nils-test-support" }
pretty_assertions = { workspace = true }
tempfile = "3"
