[package]
name = "nils-docker-tools"
version = "1.28.5"
edition.workspace = true
license.workspace = true

description = "Docker helper CLI crate for the nils-cli workspace."
repository = "https://github.com/sympoies/nils-cli"

[lib]
name = "docker_tools"
path = "src/lib.rs"

[[bin]]
name = "docker-tools"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
clap_complete = { workspace = true }
nils-build-info = { version = "1.28.5", path = "../nils-build-info" }
nils-common = { version = "1.28.5", path = "../nils-common", package = "nils-common" }
shell-words = { workspace = true }

[dev-dependencies]
nils-test-support = { version = "1.28.5", path = "../nils-test-support" }
pretty_assertions = { workspace = true }
tempfile = "3"
