[package]
name = "nils-plan-archive"
version = "1.28.21"
edition.workspace = true
license.workspace = true

description = "CLI crate for nils-plan-archive in the nils-cli workspace."
repository = "https://github.com/sympoies/nils-cli"

[lib]
name = "plan_archive"
path = "src/lib.rs"

[[bin]]
name = "plan-archive"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
clap_complete = { workspace = true }
nils-build-info = { version = "1.28.21", path = "../nils-build-info" }
indexmap = { workspace = true }
nils-common = { version = "1.28.21", path = "../nils-common", package = "nils-common" }
nils-scrub = { version = "1.28.21", path = "../nils-scrub" }
regex = "1"
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml_ng = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
nils-test-support = { version = "1.28.21", path = "../nils-test-support" }
pretty_assertions = { workspace = true }
tempfile = "3"
