[package]
name = "nils-image-processing"
version = "1.28.16"
edition.workspace = true
license.workspace = true

description = "CLI crate for nils-image-processing in the nils-cli workspace."
repository = "https://github.com/sympoies/nils-cli"

[[bin]]
name = "image-processing"
path = "src/main.rs"
[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
nils-build-info = { version = "1.28.16", path = "../nils-build-info" }
serde = { workspace = true }
serde_json = { workspace = true }

chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp"] }
nils-common = { version = "1.28.16", path = "../nils-common", package = "nils-common" }
nils-term = { version = "1.28.16", path = "../nils-term", package = "nils-term" }
resvg = "0.48"
roxmltree = "0.21"
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
nils-test-support = { version = "1.28.16", path = "../nils-test-support" }
pretty_assertions = { workspace = true }
tempfile = "3"
