#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "$repo_root" || ! -d "$repo_root" ]]; then
  echo "error: must run inside the nils-cli git work tree" >&2
  exit 2
fi

script="$repo_root/scripts/ci/detect-release-only.sh"
if [[ ! -f "$script" ]]; then
  echo "FAIL: missing release-only detector: $script" >&2
  exit 1
fi

echo "== system bash parser compatibility =="
if [[ ! -x /bin/bash ]]; then
  echo "FAIL: /bin/bash is required for release detector compatibility" >&2
  exit 1
fi
/bin/bash -n "$script"
echo "ok: release-only detector parses with /bin/bash"

producer_script="$repo_root/.agents/skills/project-bump-version-tag-release/scripts/project-bump-version-tag-release.sh"
if [[ ! -f "$producer_script" ]]; then
  echo "FAIL: missing canonical release producer: $producer_script" >&2
  exit 1
fi

tmp_root="$(mktemp -d "${TMPDIR:-/tmp}/detect-release-only.XXXXXX")"
trap 'rm -rf "$tmp_root"' EXIT

sha256_file() {
  local path="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$path" | awk '{print $1}'
  else
    shasum -a 256 "$path" | awk '{print $1}'
  fi
}

replace_text() {
  local old="$1"
  local new="$2"
  shift 2
  python3 - "$old" "$new" "$@" <<'PY'
import pathlib
import sys

old, new, *paths = sys.argv[1:]
for raw_path in paths:
    path = pathlib.Path(raw_path)
    path.write_text(path.read_text().replace(old, new))
PY
}

write_base_fixture() {
  local dir="$1"
  mkdir -p "$dir/crates/common" "$dir/crates/tool"
  git -C "$dir" init -q
  git -C "$dir" config user.name "Release CI Test"
  git -C "$dir" config user.email "release-ci@example.test"

  cat >"$dir/Cargo.toml" <<'EOF'
[workspace]
members = ["crates/common", "crates/tool"]
resolver = "2"

[workspace.package]
version = "1.2.3"

[workspace.dependencies]
nils-common = { path = "crates/common", version = "1.2.3" }
EOF
  cat >"$dir/crates/common/Cargo.toml" <<'EOF'
[package]
name = "nils-common"
version = "1.2.3"
edition = "2024"
EOF
  cat >"$dir/crates/tool/Cargo.toml" <<'EOF'
[package]
name = "nils-tool"
version = "1.2.3"
edition = "2024"

[dependencies]
nils-common = { workspace = true }
EOF
  cat >"$dir/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "nils-common"
version = "1.2.3"

[[package]]
name = "nils-tool"
version = "1.2.3"
dependencies = [
 "nils-common 1.2.3",
]
EOF
  cat >"$dir/README.md" <<'EOF'
Release with `git tag -a v1.2.3` and `git push origin v1.2.3`.
EOF
  local lock_sha
  lock_sha="$(sha256_file "$dir/Cargo.lock")"
  printf "Cargo.lock sha256: \`%s\`\n" "$lock_sha" >"$dir/THIRD_PARTY_LICENSES.md"
  printf "Cargo.lock sha256: \`%s\`\n" "$lock_sha" >"$dir/THIRD_PARTY_NOTICES.md"

  git -C "$dir" add .
  git -C "$dir" commit -q -m "chore: seed fixture"
}

write_release_commit() {
  local dir="$1"
  local old_lock_sha
  old_lock_sha="$(sha256_file "$dir/Cargo.lock")"

  replace_text "1.2.3" "1.2.4" \
    "$dir/Cargo.toml" \
    "$dir/crates/common/Cargo.toml" \
    "$dir/crates/tool/Cargo.toml" \
    "$dir/Cargo.lock" \
    "$dir/README.md"

  local new_lock_sha
  new_lock_sha="$(sha256_file "$dir/Cargo.lock")"
  replace_text "$old_lock_sha" "$new_lock_sha" \
    "$dir/THIRD_PARTY_LICENSES.md" \
    "$dir/THIRD_PARTY_NOTICES.md"

  git -C "$dir" add .
  git -C "$dir" commit -q -m "chore(release): bump cli versions to 1.2.4"
}

detect() {
  local dir="$1"
  shift
  (cd "$dir" && bash "$script" "$@")
}

assert_verdict() {
  local label="$1"
  local expected="$2"
  local dir="$3"
  shift 3
  local actual
  actual="$(detect "$dir" "$@")"
  if [[ "$actual" != "$expected" ]]; then
    echo "FAIL: $label"
    echo "  expected: $expected"
    echo "  actual:   $actual"
    exit 1
  fi
  echo "ok: $label ($expected)"
}

canonical="$tmp_root/canonical"
write_base_fixture "$canonical"
base_sha="$(git -C "$canonical" rev-parse HEAD)"
write_release_commit "$canonical"
head_sha="$(git -C "$canonical" rev-parse HEAD)"

assert_verdict "canonical release commit" true "$canonical" \
  --base "$base_sha" --head "$head_sha" --branch chore/release-1-2-4
assert_verdict "branch must match the target version" false "$canonical" \
  --base "$base_sha" --head "$head_sha" --branch chore/release-1-2-5
assert_verdict "invalid base fails closed" false "$canonical" \
  --base "$(printf '0%.0s' {1..40})" --head "$head_sha" --branch chore/release-1-2-4

extra="$tmp_root/extra"
cp -R "$canonical" "$extra"
printf 'unrelated\n' >"$extra/extra.txt"
git -C "$extra" add extra.txt
git -C "$extra" commit -q --amend --no-edit
assert_verdict "extra changed file" false "$extra" \
  --base "$base_sha" --head HEAD --branch chore/release-1-2-4

for policy_path in \
  .github/workflows/ci.yml \
  .github/scripts/release-ci-gate.cjs \
  scripts/ci/detect-release-only.sh \
  scripts/ci/release-only-checks.sh; do
  policy_name="${policy_path//\//-}"
  policy_tamper="$tmp_root/policy-${policy_name}"
  cp -R "$canonical" "$policy_tamper"
  mkdir -p "$policy_tamper/$(dirname "$policy_path")"
  printf 'untrusted policy override\n' >"$policy_tamper/$policy_path"
  git -C "$policy_tamper" add "$policy_path"
  git -C "$policy_tamper" commit -q --amend --no-edit
  assert_verdict "policy override ${policy_path}" false "$policy_tamper" \
    --base "$base_sha" --head HEAD --branch chore/release-1-2-4
done

partial="$tmp_root/partial"
cp -R "$canonical" "$partial"
replace_text 'version = "1.2.4"' 'version = "1.2.3"' "$partial/crates/common/Cargo.toml"
git -C "$partial" add crates/common/Cargo.toml
git -C "$partial" commit -q --amend --no-edit
assert_verdict "partial manifest bump" false "$partial" \
  --base "$base_sha" --head HEAD --branch chore/release-1-2-4

wrong_subject="$tmp_root/wrong-subject"
cp -R "$canonical" "$wrong_subject"
git -C "$wrong_subject" commit -q --amend -m "chore: update versions"
assert_verdict "non-canonical commit subject" false "$wrong_subject" \
  --base "$base_sha" --head HEAD --branch chore/release-1-2-4

two_commits="$tmp_root/two-commits"
cp -R "$canonical" "$two_commits"
git -C "$two_commits" commit -q --allow-empty -m "chore: second commit"
assert_verdict "more than one commit" false "$two_commits" \
  --base "$base_sha" --head HEAD --branch chore/release-1-2-4

echo "== canonical producer integration =="
producer_repo="$tmp_root/producer"
git clone -q --shared "$repo_root" "$producer_repo"
git -C "$producer_repo" config user.name "Release CI Test"
git -C "$producer_repo" config user.email "release-ci@example.test"
# Newer Git detaches automatic maintenance after a commit. A detached
# maintenance run still writing into this clone makes the EXIT trap's rm -rf
# fail with "Directory not empty" after the test has passed.
git -C "$producer_repo" config maintenance.auto false
git -C "$producer_repo" config gc.auto 0

# Local validation runs before this change is committed, so copy the current
# producer into the clone and make it part of the immutable fixture baseline.
cp "$producer_script" \
  "$producer_repo/.agents/skills/project-bump-version-tag-release/scripts/project-bump-version-tag-release.sh"
git -C "$producer_repo" add \
  .agents/skills/project-bump-version-tag-release/scripts/project-bump-version-tag-release.sh
if ! git -C "$producer_repo" diff --cached --quiet; then
  git -C "$producer_repo" commit -q --amend --no-edit
fi

producer_base="$(git -C "$producer_repo" rev-parse HEAD)"
producer_version="$(python3 - "$producer_repo/Cargo.toml" <<'PY'
import pathlib
import re
import sys

text = pathlib.Path(sys.argv[1]).read_text()
match = re.search(r'(?ms)^\[workspace[.]package\].*?^version\s*=\s*"(\d+)\.(\d+)\.(\d+)"', text)
if not match:
    raise SystemExit("workspace version missing")
major, minor, patch = map(int, match.groups())
print(f"{major}.{minor}.{patch + 1}")
PY
)"
(
  cd "$producer_repo"
  bash \
    .agents/skills/project-bump-version-tag-release/scripts/project-bump-version-tag-release.sh \
    --version "$producer_version" \
    --prepare-only
)
git -C "$producer_repo" add \
  Cargo.toml Cargo.lock README.md THIRD_PARTY_LICENSES.md THIRD_PARTY_NOTICES.md \
  crates/*/Cargo.toml
git -C "$producer_repo" commit -q \
  -m "chore(release): bump cli versions to ${producer_version}"
producer_head="$(git -C "$producer_repo" rev-parse HEAD)"
assert_verdict "real producer output" true "$producer_repo" \
  --base "$producer_base" \
  --head "$producer_head" \
  --branch "chore/release-${producer_version//./-}"

echo
echo "PASS: detect-release-only.test.sh"
