[package]
name = "nils-memo"
version = "1.28.20"
edition.workspace = true
license.workspace = true

description = "CLI crate for nils-memo in the nils-cli workspace."
repository = "https://github.com/sympoies/nils-cli"

[lib]
name = "memo"
path = "src/lib.rs"

[[bin]]
name = "memo"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
clap_complete = { workspace = true }
nils-build-info = { version = "1.28.20", path = "../nils-build-info" }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
chrono-tz = "0.10"
rusqlite = { version = "0.40.1", features = ["bundled"] }
serde = { workspace = true }
serde_json = { workspace = true }
nils-common = { version = "1.28.20", path = "../nils-common", package = "nils-common" }
nils-term = { version = "1.28.20", path = "../nils-term", package = "nils-term" }

[dev-dependencies]
nils-test-support = { version = "1.28.20", path = "../nils-test-support" }
pretty_assertions = { workspace = true }
tempfile = "3"
