[package]
name = "nils-api-grpc"
version = "1.28.13"
edition.workspace = true
license.workspace = true

description = "CLI crate for nils-api-grpc in the nils-cli workspace."
repository = "https://github.com/sympoies/nils-cli"

[[bin]]
name = "api-grpc"
path = "src/main.rs"
[dependencies]
api-testing-core = { version = "1.28.13", path = "../api-testing-core", package = "nils-api-testing-core" }
clap = { workspace = true }
clap_complete = { workspace = true }
nils-build-info = { version = "1.28.13", path = "../nils-build-info" }
nils-term = { version = "1.28.13", path = "../nils-term", package = "nils-term" }
serde_json = { workspace = true }

[dev-dependencies]
base64 = "0.23"
nils-test-support = { version = "1.28.13", path = "../nils-test-support" }
pretty_assertions = { workspace = true }
tempfile = "3"
